---
abstract: "MySQL Slow Query Log Filter\r"
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MySQL-SlowLog-Filter
no_index:
  directory:
    - inc
    - t
requires:
  File::Slurp: 0
  Getopt::Long: 0
  Pod::Usage: 0
  Time::Local: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
